import { createContext } from "react";

export default createContext({
    username: "",
    isModeAdmin: false, 
    setIsModeAdmin: () => {},
    isCollapsed: false, 
    setIsCollapsed: () => {},
    currentTabSelected: false,
    setCurrentTabSelected: () => {},
    menu : [],
    handleAdd: () => {},
    handleDelete: () => {},
    resetMenu: () => {},
    newProduct: {},
    setNewProduct: () => {},
    productSelected: {},
    setProductSelected: () => {},
    handleEdit: () => {},
    titleEditRef: {},
    basket: [],
    handleAddToBasket: () => {},
    handleDeleteBasketProduct: () => {},
    handleProductSelected: () => {},
})